### ISSUE TITLE
options.password_history not able to be set

### ISSUE THREAD

**Issue by nagoh** [yieldr/terraform-provider-auth0#40]
Hi, could very well be a case of user error here as new to TF.

Getting an error with the following 
```
resource "auth0_connection" "db_user_connection" {
  name = "customers"
  strategy = "auth0"
  options = {
    password_policy = "fair",
    password_history = {
      enabled = true
    }
  }
}
```

This is returning me the following error:

> auth0_connection.db_user_connection: 400 Bad Request: Payload validation error: 'Additional properties not allowed: enabled' on property options.password_history (Options for password history policy).

Hope someone can help
Regards

**Comment by alexkappa** [comment]
Hi @nagoh, the documentation on connections from Auth0 Management API is not defined for `password_history`. It just specifies it as an object, therefore I implemented it in both terraform and the auth0 sdk as a `map[string]interface{}` and left it up to the user to define the fields they need.

I also see some typo's from your end, which might explain the errors you're receiving. The first example you use `enabled` and in the second you use `enable`.

> Expected type integer but found type string' on property options.password_history.size.

Try `size = 5` instead (without the quotes).

> Expected type boolean but found type string' on property options.password_history.enable

Try `enable = true`. (again, no quotes).

**Comment by nagoh** [comment]
Hi - thanks for the response. 

Yeah sorry I didn't articulate that 2nd part of my issue well. 

This is the section that I used:
```
    password_history = {
      enable = true,
      size = 5
    },
```
And I got:
> auth0_connection.db_user_connection: 400 Bad Request: Payload validation error: 'Expected type integer but found type string' on property options.password_history.size. (also) Payload validation error: 'Expected type boolean but found type string' on property options.password_history.enable.

**Comment by nagoh** [comment]
There is simply an `object` type (rather unhelpfully) defined here: https://auth0.com/docs/api/management/v2#!/Connections/post_connections

Though, if you inspect the JSON payload from the GET endpoint (when debugging via the web admin console), those values (enable & size) are being returned as a boolean and number respectfully. 

If you want to get that one done, I'd be happy to help cleaning up the others (i.e. `password_no_personal_info` property suffers a similar fate).

**Comment by alexkappa** [comment]
@nagoh the latest release should address this issues and you should be able to set password history correctly. Please let me know if you have any feedback!

**Comment by kevinohara80** [comment]
I'm still getting this issue in `0.1.11`

My example:

```
resource "auth0_connection" "users" {
  name     = "Users Database"
  strategy = "auth0"

  options = {
    password_policy = "good"
    disable_signup  = true

    password_history = {
      enable = false
      size   = 0
    }

    brute_force_protection = "true"
  }

  enabled_clients = [
    "${auth0_client.web_portal.id}",
  ]
}
```

Errors with:

```
Error: Error applying plan:

1 error(s) occurred:

* auth0_connection.users: 1 error(s) occurred:

* auth0_connection.users: 400 Bad Request: Payload validation error: 'Expected 
type integer but found type null' on property options.password_history.size. (also) 
Payload validation error: 'Expected type boolean but found type null' on property
options.password_history.enable.
```

**Comment by kevinohara80** [comment]
Oh I see now...The [example](https://github.com/yieldr/terraform-provider-auth0/blob/master/example/connection/main.tf) still has the properties as bool and number. That should be updated since it's expecting strings only:

```
password_history = {
  enable = "false"
  size   = "0"
}
```

I can send a PR for that if you like.
